name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.1-alpine
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: go test ./...
